spring:
  application:
    name: test_prometheus
  docker:
    compose:
      enabled: true

management:
  export:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # ????????? ??? actuator endpoints ????? HTTP (?? ????????? ????? ??? ??????)
  endpoint:
    health:
      show-details: always # ?????? /actuator/health ?????????, ? ???????????? ???? ???????? (????????, ????????? ?????, ?????, ? ?.?.)
    shutdown:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true